### PR TITLE
Update db.py

### PR DESCRIPTION
**Pull request by ameligrana**
this should fix issue https://github.com/minamotorin/twint/issues/3#issue-1125224774

### CODE REVIEW

**Comment by minamotorin** [comment]
When I opened #3, I seem to have misunderstood `config.Database="filename"` as `twint.run.db`, sorry.
I don't know what was the problem with `db.py`, but I will merge this PR if I understand it.

@Tortar
Can you show me an example code for the problem resolved in this PR?

**Comment by Tortar** [comment]
writing in terminal

`twint -s a -db a.db`

gives 

```
File "\.", line 293, in tweets
    cursor.execute(query, (Tweet.id, int(reply['user_id']), reply['username']))
KeyError: 'user_id'
```

after fixing it it will through exception on the other two lines of code because the one with mentions is a dict of dicts and so it can't be used the join method on it tweet.place is a dict and so can't be inserted in the db if you don't convert it in string before that

**Comment by minamotorin** [comment]
@Tortar
Thanks! I confirmed the  behavior.
But I think it's better to put  this PR on hold.
The reason is followings.

- #3 was written with the intention of #13 (my explanation was insufficient)
- The cause of #3 is considered to be the same as the cause of #13
- Then, fix for #3 and fix for #13 can conflict
- The fix for #13 is more fundamental, so it should be prioritized

After fixing #13 completely, if this PR still useful, I'll merge this PR.

Any other opinions are welcome.

**Comment by minamotorin** [comment]
I merge this because I think #13 isn't fixed for a while.

**Pull request merged**
